
interface SearchResult {
  id: string;
  name: string;
  location: string;
  matchScore: number;
  insights: string[];
  status: "Live" | "Archived";
  updated: string;
}

// Mock data - replace with actual API calls when backend is ready
export const candidateRecords: SearchResult[] = [
  { id: "1", name: "Johnathan Smith", location: "Lagos, Nigeria", matchScore: 92, insights: ["Utilities account", "Property filings", "Alias detected"], status: "Live", updated: "2h ago" },
  { id: "2", name: "Joanna Smith", location: "Nairobi, Kenya", matchScore: 78, insights: ["Business registration", "Social media"], status: "Live", updated: "5h ago" },
  { id: "3", name: "John Smith", location: "Cape Town, South Africa", matchScore: 66, insights: ["Court docket", "Professional license"], status: "Archived", updated: "1d ago" },
  { id: "4", name: "Michael Johnson", location: "Johannesburg, South Africa", matchScore: 95, insights: ["Property filings", "Vehicle registration", "Voter record"], status: "Live", updated: "1h ago" },
  { id: "5", name: "Emily Davis", location: "Chicago, IL", matchScore: 88, insights: ["Professional license", "Court docket"], status: "Live", updated: "3h ago" },
  { id: "6", name: "Robert Williams", location: "Houston, TX", matchScore: 74, insights: ["Business registration", "Utilities account"], status: "Live", updated: "6h ago" },
  { id: "7", name: "Sarah Brown", location: "Phoenix, AZ", matchScore: 81, insights: ["Social media", "Property filings", "Alias detected"], status: "Live", updated: "4h ago" },
  { id: "8", name: "David Martinez", location: "Cairo, Egypt", matchScore: 69, insights: ["Court docket"], status: "Archived", updated: "2d ago" },
  { id: "9", name: "Jennifer Garcia", location: "Accra, Ghana", matchScore: 85, insights: ["Voter record", "Professional license", "Business registration"], status: "Live", updated: "2h ago" },
  { id: "10", name: "James Wilson", location: "Dakar, Senegal", matchScore: 91, insights: ["Vehicle registration", "Property filings"], status: "Live", updated: "1h ago" },
  { id: "11", name: "Linda Anderson", location: "Dallas, TX", matchScore: 77, insights: ["Utilities account", "Social media"], status: "Live", updated: "5h ago" },
  { id: "12", name: "William Taylor", location: "Casablanca, Morocco", matchScore: 63, insights: ["Court docket", "Alias detected"], status: "Archived", updated: "3d ago" },
  { id: "13", name: "Elizabeth Thomas", location: "Rabat, Morocco", matchScore: 89, insights: ["Property filings", "Professional license", "Voter record"], status: "Live", updated: "2h ago" },
  { id: "14", name: "Charles Jackson", location: "Marrakech, Morocco", matchScore: 72, insights: ["Business registration"], status: "Live", updated: "8h ago" },
  { id: "15", name: "Patricia White", location: "Kampala, Uganda", matchScore: 94, insights: ["Utilities account", "Vehicle registration", "Property filings"], status: "Live", updated: "30m ago" },
  { id: "16", name: "Christopher Harris", location: "Addis Ababa, Ethiopia", matchScore: 67, insights: ["Social media", "Court docket"], status: "Archived", updated: "4d ago" },
  { id: "17", name: "Barbara Clark", location: "Lusaka, Zambia", matchScore: 83, insights: ["Professional license", "Business registration"], status: "Live", updated: "3h ago" },
  { id: "18", name: "Daniel Lewis", location: "Harare, Zimbabwe", matchScore: 96, insights: ["Property filings", "Voter record", "Alias detected", "Social media"], status: "Live", updated: "45m ago" },
  { id: "19", name: "Susan Robinson", location: "Windhoek, Namibia", matchScore: 71, insights: ["Utilities account"], status: "Live", updated: "7h ago" },
  { id: "20", name: "Matthew Walker", location: "Maputo, Mozambique", matchScore: 86, insights: ["Vehicle registration", "Court docket", "Professional license"], status: "Live", updated: "2h ago" },
  { id: "21", name: "Jessica Hall", location: "Algiers, Algeria", matchScore: 79, insights: ["Business registration", "Property filings"], status: "Live", updated: "4h ago" },
  { id: "22", name: "Anthony Young", location: "Tunis, Tunisia", matchScore: 64, insights: ["Social media", "Alias detected"], status: "Archived", updated: "5d ago" },
  { id: "23", name: "Nancy King", location: "Tripoli, Libya", matchScore: 90, insights: ["Voter record", "Utilities account", "Professional license"], status: "Live", updated: "1h ago" },
  { id: "24", name: "Mark Wright", location: "Kigali, Rwanda", matchScore: 75, insights: ["Court docket", "Vehicle registration"], status: "Live", updated: "6h ago" },
  { id: "25", name: "Karen Scott", location: "Bujumbura, Burundi", matchScore: 82, insights: ["Property filings", "Business registration"], status: "Live", updated: "3h ago" },
  { id: "26", name: "Steven Green", location: "Monrovia, Liberia", matchScore: 68, insights: ["Social media"], status: "Archived", updated: "2d ago" },
  { id: "27", name: "Betty Adams", location: "Freetown, Sierra Leone", matchScore: 93, insights: ["Professional license", "Voter record", "Alias detected"], status: "Live", updated: "1h ago" },
  { id: "28", name: "Paul Baker", location: "Conakry, Guinea", matchScore: 76, insights: ["Utilities account", "Court docket"], status: "Live", updated: "5h ago" },
  { id: "29", name: "Dorothy Nelson", location: "Brazzaville, Republic of the Congo", matchScore: 87, insights: ["Vehicle registration", "Property filings", "Social media"], status: "Live", updated: "2h ago" },
  { id: "30", name: "Andrew Carter", location: "Kinshasa, DR Congo", matchScore: 61, insights: ["Business registration"], status: "Archived", updated: "6d ago" },
  { id: "31", name: "Margaret Mitchell", location: "Luanda, Angola", matchScore: 84, insights: ["Professional license", "Voter record"], status: "Live", updated: "4h ago" },
  { id: "32", name: "Joshua Perez", location: "Antananarivo, Madagascar", matchScore: 73, insights: ["Court docket", "Alias detected"], status: "Live", updated: "7h ago" },
  { id: "33", name: "Sandra Roberts", location: "Lome, Togo", matchScore: 89, insights: ["Utilities account", "Property filings", "Vehicle registration"], status: "Live", updated: "2h ago" },
  { id: "34", name: "Kevin Turner", location: "Porto-Novo, Benin", matchScore: 65, insights: ["Social media", "Business registration"], status: "Archived", updated: "3d ago" },
  { id: "35", name: "Ashley Phillips", location: "Cotonou, Benin", matchScore: 91, insights: ["Professional license", "Court docket", "Voter record"], status: "Live", updated: "1h ago" },
  { id: "36", name: "Brian Campbell", location: "Bamako, Mali", matchScore: 78, insights: ["Property filings", "Alias detected"], status: "Live", updated: "5h ago" },
  { id: "37", name: "Kimberly Parker", location: "Niamey, Niger", matchScore: 70, insights: ["Utilities account"], status: "Live", updated: "9h ago" },
  { id: "38", name: "George Evans", location: "Ouagadougou, Burkina Faso", matchScore: 95, insights: ["Vehicle registration", "Business registration", "Social media", "Court docket"], status: "Live", updated: "30m ago" },
  { id: "39", name: "Donna Edwards", location: "Mogadishu, Somalia", matchScore: 62, insights: ["Professional license"], status: "Archived", updated: "4d ago" },
  { id: "40", name: "Edward Collins", location: "Djibouti, Djibouti", matchScore: 88, insights: ["Property filings", "Voter record", "Alias detected"], status: "Live", updated: "2h ago" },
  { id: "41", name: "Michelle Stewart", location: "Asmara, Eritrea", matchScore: 80, insights: ["Utilities account", "Court docket"], status: "Live", updated: "4h ago" },
  { id: "42", name: "Ronald Sanchez", location: "Gaborone, Botswana", matchScore: 74, insights: ["Business registration", "Social media"], status: "Live", updated: "6h ago" },
  { id: "43", name: "Carol Morris", location: "Maseru, Lesotho", matchScore: 97, insights: ["Professional license", "Property filings", "Vehicle registration", "Voter record"], status: "Live", updated: "20m ago" },
  { id: "44", name: "Timothy Rogers", location: "Mbabane, Eswatini", matchScore: 66, insights: ["Court docket", "Alias detected"], status: "Archived", updated: "5d ago" },
  { id: "45", name: "Amanda Reed", location: "Praia, Cape Verde", matchScore: 85, insights: ["Utilities account", "Business registration"], status: "Live", updated: "3h ago" },
  { id: "46", name: "Jason Cook", location: "Nouakchott, Mauritania", matchScore: 77, insights: ["Social media", "Professional license"], status: "Live", updated: "5h ago" },
  { id: "47", name: "Stephanie Morgan", location: "Juba, South Sudan", matchScore: 92, insights: ["Property filings", "Vehicle registration", "Voter record"], status: "Live", updated: "1h ago" },
  { id: "48", name: "Jeffrey Bell", location: "N'Djamena, Chad", matchScore: 69, insights: ["Court docket"], status: "Archived", updated: "2d ago" },
  { id: "49", name: "Rebecca Murphy", location: "Sao Tome, Sao Tome and Principe", matchScore: 83, insights: ["Alias detected", "Utilities account", "Business registration"], status: "Live", updated: "4h ago" },
  { id: "50", name: "Ryan Bailey", location: "Victoria, Seychelles", matchScore: 71, insights: ["Social media", "Professional license"], status: "Live", updated: "7h ago" },
  { id: "51", name: "Laura Rivera", location: "Port Louis, Mauritius", matchScore: 86, insights: ["Property filings", "Court docket", "Voter record"], status: "Live", updated: "2h ago" },
  { id: "52", name: "Gary Cooper", location: "Dar es Salaam, Tanzania", matchScore: 63, insights: ["Vehicle registration"], status: "Archived", updated: "6d ago" },
  { id: "53", name: "Deborah Richardson", location: "Tangier, Morocco", matchScore: 94, insights: ["Utilities account", "Business registration", "Alias detected"], status: "Live", updated: "45m ago" },
  { id: "54", name: "Jacob Cox", location: "Kisangani, DR Congo", matchScore: 75, insights: ["Social media", "Professional license"], status: "Live", updated: "6h ago" },
  { id: "55", name: "Heather Howard", location: "Aurora, CO", matchScore: 81, insights: ["Property filings", "Court docket"], status: "Live", updated: "3h ago" },
  { id: "56", name: "Nicholas Ward", location: "Anaheim, CA", matchScore: 67, insights: ["Voter record", "Vehicle registration"], status: "Archived", updated: "3d ago" },
  { id: "57", name: "Sharon Torres", location: "Honolulu, HI", matchScore: 90, insights: ["Utilities account", "Business registration", "Professional license"], status: "Live", updated: "1h ago" },
  { id: "58", name: "Eric Peterson", location: "Santa Ana, CA", matchScore: 72, insights: ["Social media", "Alias detected"], status: "Live", updated: "8h ago" },
  { id: "59", name: "Cynthia Gray", location: "St. Louis, MO", matchScore: 87, insights: ["Property filings", "Court docket", "Voter record"], status: "Live", updated: "2h ago" },
  { id: "60", name: "Stephen Ramirez", location: "Riverside, CA", matchScore: 64, insights: ["Vehicle registration"], status: "Archived", updated: "4d ago" },
  { id: "61", name: "Angela James", location: "Corpus Christi, TX", matchScore: 93, insights: ["Utilities account", "Professional license", "Business registration"], status: "Live", updated: "1h ago" },
  { id: "62", name: "Larry Watson", location: "Lexington, KY", matchScore: 79, insights: ["Social media", "Property filings"], status: "Live", updated: "4h ago" },
  { id: "63", name: "Kathleen Brooks", location: "Pittsburgh, PA", matchScore: 70, insights: ["Court docket", "Alias detected"], status: "Live", updated: "9h ago" },
  { id: "64", name: "Dennis Kelly", location: "Anchorage, AK", matchScore: 96, insights: ["Voter record", "Vehicle registration", "Utilities account", "Professional license"], status: "Live", updated: "35m ago" },
  { id: "65", name: "Amy Sanders", location: "Stockton, CA", matchScore: 61, insights: ["Business registration"], status: "Archived", updated: "7d ago" },
  { id: "66", name: "Jerry Price", location: "Cincinnati, OH", matchScore: 84, insights: ["Social media", "Property filings", "Court docket"], status: "Live", updated: "3h ago" },
  { id: "67", name: "Brenda Bennett", location: "St. Paul, MN", matchScore: 76, insights: ["Alias detected", "Voter record"], status: "Live", updated: "5h ago" },
  { id: "68", name: "Scott Wood", location: "Toledo, OH", matchScore: 88, insights: ["Utilities account", "Vehicle registration", "Professional license"], status: "Live", updated: "2h ago" },
  { id: "69", name: "Pamela Barnes", location: "Newark, NJ", matchScore: 65, insights: ["Business registration", "Social media"], status: "Archived", updated: "5d ago" },
  { id: "70", name: "Benjamin Ross", location: "Greensboro, NC", matchScore: 91, insights: ["Property filings", "Court docket", "Voter record"], status: "Live", updated: "1h ago" },
  { id: "71", name: "Virginia Henderson", location: "Plano, TX", matchScore: 73, insights: ["Alias detected", "Utilities account"], status: "Live", updated: "7h ago" },
  { id: "72", name: "Alexander Coleman", location: "Henderson, NV", matchScore: 82, insights: ["Vehicle registration", "Professional license", "Business registration"], status: "Live", updated: "4h ago" },
  { id: "73", name: "Diane Jenkins", location: "Lincoln, NE", matchScore: 68, insights: ["Social media", "Property filings"], status: "Archived", updated: "2d ago" },
  { id: "74", name: "Raymond Perry", location: "Buffalo, NY", matchScore: 95, insights: ["Court docket", "Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "40m ago" },
  { id: "75", name: "Julie Powell", location: "Fort Wayne, IN", matchScore: 77, insights: ["Vehicle registration", "Professional license"], status: "Live", updated: "5h ago" },
  { id: "76", name: "Eugene Long", location: "Jersey City, NJ", matchScore: 69, insights: ["Business registration"], status: "Archived", updated: "3d ago" },
  { id: "77", name: "Janet Patterson", location: "Chula Vista, CA", matchScore: 89, insights: ["Social media", "Property filings", "Court docket"], status: "Live", updated: "2h ago" },
  { id: "78", name: "Philip Hughes", location: "Orlando, FL", matchScore: 80, insights: ["Voter record", "Alias detected"], status: "Live", updated: "4h ago" },
  { id: "79", name: "Marie Flores", location: "Durham, NC", matchScore: 74, insights: ["Utilities account", "Vehicle registration"], status: "Live", updated: "6h ago" },
  { id: "80", name: "Roy Washington", location: "Laredo, TX", matchScore: 97, insights: ["Professional license", "Business registration", "Property filings", "Social media"], status: "Live", updated: "15m ago" },
  { id: "81", name: "Frances Butler", location: "Madison, WI", matchScore: 62, insights: ["Court docket"], status: "Archived", updated: "6d ago" },
  { id: "82", name: "Wayne Simmons", location: "Lubbock, TX", matchScore: 85, insights: ["Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "3h ago" },
  { id: "83", name: "Ann Foster", location: "Chandler, AZ", matchScore: 78, insights: ["Vehicle registration", "Professional license"], status: "Live", updated: "5h ago" },
  { id: "84", name: "Billy Gonzales", location: "Scottsdale, AZ", matchScore: 71, insights: ["Business registration", "Social media"], status: "Live", updated: "8h ago" },
  { id: "85", name: "Evelyn Bryant", location: "Glendale, AZ", matchScore: 92, insights: ["Property filings", "Court docket", "Voter record"], status: "Live", updated: "1h ago" },
  { id: "86", name: "Russell Alexander", location: "Irving, TX", matchScore: 66, insights: ["Alias detected"], status: "Archived", updated: "4d ago" },
  { id: "87", name: "Jean Russell", location: "Chesapeake, VA", matchScore: 83, insights: ["Utilities account", "Vehicle registration", "Professional license"], status: "Live", updated: "4h ago" },
  { id: "88", name: "Louis Griffin", location: "North Las Vegas, NV", matchScore: 75, insights: ["Business registration", "Property filings"], status: "Live", updated: "6h ago" },
  { id: "89", name: "Alice Diaz", location: "Fremont, CA", matchScore: 90, insights: ["Social media", "Court docket", "Voter record"], status: "Live", updated: "2h ago" },
  { id: "90", name: "Randy Hayes", location: "Gilbert, AZ", matchScore: 63, insights: ["Alias detected", "Utilities account"], status: "Archived", updated: "5d ago" },
  { id: "91", name: "Judy Myers", location: "San Bernardino, CA", matchScore: 86, insights: ["Vehicle registration", "Professional license", "Business registration"], status: "Live", updated: "3h ago" },
  { id: "92", name: "Harry Ford", location: "Boise, ID", matchScore: 79, insights: ["Property filings", "Social media"], status: "Live", updated: "4h ago" },
  { id: "93", name: "Teresa Hamilton", location: "Birmingham, AL", matchScore: 94, insights: ["Court docket", "Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "50m ago" },
  { id: "94", name: "Albert Graham", location: "Spokane, WA", matchScore: 67, insights: ["Vehicle registration"], status: "Archived", updated: "3d ago" },
  { id: "95", name: "Gloria Sullivan", location: "Rochester, NY", matchScore: 81, insights: ["Professional license", "Business registration", "Property filings"], status: "Live", updated: "4h ago" },
  { id: "96", name: "Joe Wallace", location: "Des Moines, IA", matchScore: 72, insights: ["Social media", "Court docket"], status: "Live", updated: "7h ago" },
  { id: "97", name: "Theresa West", location: "Modesto, CA", matchScore: 88, insights: ["Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "2h ago" },
  { id: "98", name: "Gerald Cole", location: "Tacoma, WA", matchScore: 64, insights: ["Vehicle registration", "Professional license"], status: "Archived", updated: "6d ago" },
  { id: "99", name: "Rose Jordan", location: "Fontana, CA", matchScore: 93, insights: ["Business registration", "Property filings", "Social media"], status: "Live", updated: "1h ago" },
  { id: "100", name: "Arthur Owens", location: "Moreno Valley, CA", matchScore: 76, insights: ["Court docket", "Voter record"], status: "Live", updated: "5h ago" },
  { id: "101", name: "Janice Reynolds", location: "Fayetteville, NC", matchScore: 70, insights: ["Alias detected", "Utilities account"], status: "Live", updated: "9h ago" },
  { id: "102", name: "Lawrence Hunt", location: "Yonkers, NY", matchScore: 96, insights: ["Vehicle registration", "Professional license", "Business registration", "Property filings"], status: "Live", updated: "25m ago" },
  { id: "103", name: "Lori Nichols", location: "Huntsville, AL", matchScore: 61, insights: ["Social media"], status: "Archived", updated: "7d ago" },
  { id: "104", name: "Carl Simpson", location: "Glendale, CA", matchScore: 84, insights: ["Court docket", "Voter record", "Alias detected"], status: "Live", updated: "3h ago" },
  { id: "105", name: "Marilyn Duncan", location: "Aurora, IL", matchScore: 77, insights: ["Utilities account", "Vehicle registration"], status: "Live", updated: "5h ago" },
  { id: "106", name: "Bruce Spencer", location: "Amarillo, TX", matchScore: 89, insights: ["Professional license", "Business registration", "Property filings"], status: "Live", updated: "2h ago" },
  { id: "107", name: "Kathryn Crawford", location: "Oxnard, CA", matchScore: 65, insights: ["Social media", "Court docket"], status: "Archived", updated: "4d ago" },
  { id: "108", name: "Clarence Gardner", location: "Knoxville, TN", matchScore: 91, insights: ["Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "1h ago" },
  { id: "109", name: "Sara Lawrence", location: "Grand Rapids, MI", matchScore: 73, insights: ["Vehicle registration", "Professional license"], status: "Live", updated: "7h ago" },
  { id: "110", name: "Jesse Guerrero", location: "Bakersfield, CA", matchScore: 82, insights: ["Business registration", "Property filings", "Social media"], status: "Live", updated: "4h ago" },
  { id: "111", name: "Frances Lane", location: "Montgomery, AL", matchScore: 68, insights: ["Court docket"], status: "Archived", updated: "2d ago" },
  { id: "112", name: "Willie Harper", location: "Shreveport, LA", matchScore: 95, insights: ["Voter record", "Alias detected", "Utilities account", "Vehicle registration"], status: "Live", updated: "35m ago" },
  { id: "113", name: "Lillian Stone", location: "Mobile, AL", matchScore: 78, insights: ["Professional license", "Business registration"], status: "Live", updated: "5h ago" },
  { id: "114", name: "Terry Gordon", location: "Little Rock, AR", matchScore: 69, insights: ["Property filings", "Social media"], status: "Archived", updated: "5d ago" },
  { id: "115", name: "Catherine Warren", location: "Grand Prairie, TX", matchScore: 87, insights: ["Court docket", "Voter record", "Alias detected"], status: "Live", updated: "2h ago" },
  { id: "116", name: "Randy Hawkins", location: "Tallahassee, FL", matchScore: 80, insights: ["Utilities account", "Vehicle registration"], status: "Live", updated: "4h ago" },
  { id: "117", name: "Mildred Stephens", location: "Salt Lake City, UT", matchScore: 74, insights: ["Professional license", "Business registration"], status: "Live", updated: "6h ago" },
  { id: "118", name: "Ernest Sims", location: "Huntington Beach, CA", matchScore: 97, insights: ["Property filings", "Social media", "Court docket", "Voter record"], status: "Live", updated: "10m ago" },
  { id: "119", name: "Irene Tucker", location: "Overland Park, KS", matchScore: 62, insights: ["Alias detected"], status: "Archived", updated: "6d ago" },
  { id: "120", name: "Samuel Porter", location: "Worcester, MA", matchScore: 85, insights: ["Utilities account", "Vehicle registration", "Professional license"], status: "Live", updated: "3h ago" },
  { id: "121", name: "Cheryl Hunter", location: "Brownsville, TX", matchScore: 71, insights: ["Business registration", "Property filings"], status: "Live", updated: "8h ago" },
  { id: "122", name: "Craig Hicks", location: "McKinney, TX", matchScore: 92, insights: ["Social media", "Court docket", "Voter record"], status: "Live", updated: "1h ago" },
  { id: "123", name: "Ruth Shaw", location: "Newport News, VA", matchScore: 66, insights: ["Alias detected", "Utilities account"], status: "Archived", updated: "3d ago" },
  { id: "124", name: "Johnny Holmes", location: "Providence, RI", matchScore: 83, insights: ["Vehicle registration", "Professional license", "Business registration"], status: "Live", updated: "4h ago" },
  { id: "125", name: "Annie Rice", location: "Pembroke Pines, FL", matchScore: 75, insights: ["Property filings", "Social media"], status: "Live", updated: "6h ago" },
  { id: "126", name: "Gregory Robertson", location: "Rancho Cucamonga, CA", matchScore: 90, insights: ["Court docket", "Voter record", "Alias detected"], status: "Live", updated: "2h ago" },
  { id: "127", name: "Hazel Black", location: "Santa Clarita, CA", matchScore: 63, insights: ["Utilities account"], status: "Archived", updated: "4d ago" },
  { id: "128", name: "Martin Boyd", location: "Cape Coral, FL", matchScore: 86, insights: ["Vehicle registration", "Professional license", "Business registration"], status: "Live", updated: "3h ago" },
  { id: "129", name: "Andrea Mason", location: "Sioux Falls, SD", matchScore: 79, insights: ["Property filings", "Social media", "Court docket"], status: "Live", updated: "4h ago" },
  { id: "130", name: "Earl Freeman", location: "Peoria, AZ", matchScore: 94, insights: ["Voter record", "Alias detected", "Utilities account", "Vehicle registration"], status: "Live", updated: "55m ago" },
  { id: "131", name: "Wanda Arnold", location: "Tempe, AZ", matchScore: 67, insights: ["Professional license"], status: "Archived", updated: "5d ago" },
  { id: "132", name: "Victor Burns", location: "Springfield, MO", matchScore: 81, insights: ["Business registration", "Property filings", "Social media"], status: "Live", updated: "4h ago" },
  { id: "133", name: "Shirley George", location: "Corona, CA", matchScore: 72, insights: ["Court docket", "Voter record"], status: "Live", updated: "7h ago" },
  { id: "134", name: "Stanley Henry", location: "Eugene, OR", matchScore: 88, insights: ["Alias detected", "Utilities account", "Vehicle registration"], status: "Live", updated: "2h ago" },
  { id: "135", name: "Rosa Medina", location: "Lancaster, CA", matchScore: 64, insights: ["Professional license", "Business registration"], status: "Archived", updated: "6d ago" },
  { id: "136", name: "Wayne Harper", location: "Palmdale, CA", matchScore: 93, insights: ["Property filings", "Social media", "Court docket"], status: "Live", updated: "1h ago" },
  { id: "137", name: "Victoria Knight", location: "Salinas, CA", matchScore: 76, insights: ["Voter record", "Alias detected"], status: "Live", updated: "5h ago" },
  { id: "138", name: "Randy Fox", location: "Springfield, MA", matchScore: 70, insights: ["Utilities account", "Vehicle registration"], status: "Live", updated: "9h ago" },
  { id: "139", name: "Ruby Rose", location: "Pasadena, TX", matchScore: 96, insights: ["Professional license", "Business registration", "Property filings", "Social media"], status: "Live", updated: "30m ago" },
  { id: "140", name: "Eddie Lynch", location: "Pomona, CA", matchScore: 61, insights: ["Court docket"], status: "Archived", updated: "7d ago" },
  { id: "141", name: "Christina Elliott", location: "Hayward, CA", matchScore: 84, insights: ["Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "3h ago" },
  { id: "142", name: "Phillip Webb", location: "Rockford, IL", matchScore: 77, insights: ["Vehicle registration", "Professional license"], status: "Live", updated: "5h ago" },
  { id: "143", name: "Norma Simpson", location: "Joliet, IL", matchScore: 89, insights: ["Business registration", "Property filings", "Social media"], status: "Live", updated: "2h ago" },
  { id: "144", name: "Peter Ruiz", location: "Paterson, NJ", matchScore: 65, insights: ["Court docket", "Voter record"], status: "Archived", updated: "4d ago" },
  { id: "145", name: "Bonnie Murray", location: "Savannah, GA", matchScore: 91, insights: ["Alias detected", "Utilities account", "Vehicle registration"], status: "Live", updated: "1h ago" },
  { id: "146", name: "Carlos Day", location: "Bridgeport, CT", matchScore: 73, insights: ["Professional license", "Business registration"], status: "Live", updated: "7h ago" },
  { id: "147", name: "Beatrice Morrison", location: "Lakewood, CO", matchScore: 82, insights: ["Property filings", "Social media", "Court docket"], status: "Live", updated: "4h ago" },
  { id: "148", name: "Sean Hansen", location: "Hollywood, FL", matchScore: 68, insights: ["Voter record"], status: "Archived", updated: "2d ago" },
  { id: "149", name: "Paula Matthews", location: "Sunnyvale, CA", matchScore: 95, insights: ["Alias detected", "Utilities account", "Vehicle registration", "Professional license"], status: "Live", updated: "40m ago" },
  { id: "150", name: "Keith Vasquez", location: "Bellevue, WA", matchScore: 78, insights: ["Business registration", "Property filings"], status: "Live", updated: "5h ago" },
  { id: "151", name: "Emily Castillo", location: "Concord, CA", matchScore: 69, insights: ["Social media", "Court docket"], status: "Archived", updated: "5d ago" },
  { id: "152", name: "Howard Snyder", location: "Miramar, FL", matchScore: 87, insights: ["Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "2h ago" },
  { id: "153", name: "Gloria Wheeler", location: "Roseville, CA", matchScore: 80, insights: ["Vehicle registration", "Professional license"], status: "Live", updated: "4h ago" },
  { id: "154", name: "Fred Kim", location: "Olathe, KS", matchScore: 74, insights: ["Business registration", "Property filings"], status: "Live", updated: "6h ago" },
  { id: "155", name: "Tiffany Wagner", location: "Naperville, IL", matchScore: 97, insights: ["Social media", "Court docket", "Voter record", "Alias detected"], status: "Live", updated: "15m ago" },
  { id: "156", name: "Alan Castro", location: "Thornton, CO", matchScore: 62, insights: ["Utilities account"], status: "Archived", updated: "6d ago" },
  { id: "157", name: "Debra Mills", location: "Ontario, CA", matchScore: 85, insights: ["Vehicle registration", "Professional license", "Business registration"], status: "Live", updated: "3h ago" },
  { id: "158", name: "Norman Ortiz", location: "Waco, TX", matchScore: 71, insights: ["Property filings", "Social media"], status: "Live", updated: "8h ago" },
  { id: "159", name: "Carmen Garza", location: "Garden Grove, CA", matchScore: 92, insights: ["Court docket", "Voter record", "Alias detected"], status: "Live", updated: "1h ago" },
  { id: "160", name: "Shawn Ramos", location: "Oceanside, CA", matchScore: 66, insights: ["Utilities account", "Vehicle registration"], status: "Archived", updated: "3d ago" },
  { id: "161", name: "Leslie Reyes", location: "Elk Grove, CA", matchScore: 83, insights: ["Professional license", "Business registration", "Property filings"], status: "Live", updated: "4h ago" },
  { id: "162", name: "Dale Vargas", location: "Santa Rosa, CA", matchScore: 75, insights: ["Social media", "Court docket"], status: "Live", updated: "6h ago" },
  { id: "163", name: "Josephine Park", location: "Rancho Cordova, CA", matchScore: 90, insights: ["Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "2h ago" },
  { id: "164", name: "Henry Cruz", location: "Cary, NC", matchScore: 63, insights: ["Vehicle registration"], status: "Archived", updated: "4d ago" },
  { id: "165", name: "Juanita Fisher", location: "Carrollton, TX", matchScore: 86, insights: ["Professional license", "Business registration", "Property filings"], status: "Live", updated: "3h ago" },
  { id: "166", name: "Patrick Riley", location: "Frisco, TX", matchScore: 79, insights: ["Social media", "Court docket", "Voter record"], status: "Live", updated: "4h ago" },
  { id: "167", name: "Lucille Gomez", location: "Port St. Lucie, FL", matchScore: 94, insights: ["Alias detected", "Utilities account", "Vehicle registration", "Professional license"], status: "Live", updated: "50m ago" },
  { id: "168", name: "Jack Hernandez", location: "Peoria, IL", matchScore: 67, insights: ["Business registration"], status: "Archived", updated: "5d ago" },
  { id: "169", name: "Clara Lee", location: "Denton, TX", matchScore: 81, insights: ["Property filings", "Social media", "Court docket"], status: "Live", updated: "4h ago" },
  { id: "170", name: "Jimmy Torres", location: "Midland, TX", matchScore: 72, insights: ["Voter record", "Alias detected"], status: "Live", updated: "7h ago" },
  { id: "171", name: "Esther Martinez", location: "Dayton, OH", matchScore: 88, insights: ["Utilities account", "Vehicle registration", "Professional license"], status: "Live", updated: "2h ago" },
  { id: "172", name: "Todd Anderson", location: "Enterprise, NV", matchScore: 64, insights: ["Business registration", "Property filings"], status: "Archived", updated: "6d ago" },
  { id: "173", name: "Marjorie Wilson", location: "Murfreesboro, TN", matchScore: 93, insights: ["Social media", "Court docket", "Voter record"], status: "Live", updated: "1h ago" },
  { id: "174", name: "Frank Taylor", location: "South Bend, IN", matchScore: 76, insights: ["Alias detected", "Utilities account"], status: "Live", updated: "5h ago" },
  { id: "175", name: "Geraldine Thomas", location: "Norman, OK", matchScore: 70, insights: ["Vehicle registration", "Professional license"], status: "Live", updated: "9h ago" },
  { id: "176", name: "Leroy Jackson", location: "Fargo, ND", matchScore: 96, insights: ["Business registration", "Property filings", "Social media", "Court docket"], status: "Live", updated: "25m ago" },
  { id: "177", name: "Sylvia White", location: "Columbia, SC", matchScore: 61, insights: ["Voter record"], status: "Archived", updated: "7d ago" },
  { id: "178", name: "Marcus Harris", location: "Abilene, TX", matchScore: 84, insights: ["Alias detected", "Utilities account", "Vehicle registration"], status: "Live", updated: "3h ago" },
  { id: "179", name: "Edith Martin", location: "Reno, NV", matchScore: 77, insights: ["Professional license", "Business registration"], status: "Live", updated: "5h ago" },
  { id: "180", name: "Melvin Thompson", location: "Visalia, CA", matchScore: 89, insights: ["Property filings", "Social media", "Court docket"], status: "Live", updated: "2h ago" },
  { id: "181", name: "Marion Garcia", location: "Victorville, CA", matchScore: 65, insights: ["Voter record", "Alias detected"], status: "Archived", updated: "4d ago" },
  { id: "182", name: "Oscar Martinez", location: "Charleston, SC", matchScore: 91, insights: ["Utilities account", "Vehicle registration", "Professional license"], status: "Live", updated: "1h ago" },
  { id: "183", name: "Edna Robinson", location: "Clarksville, TN", matchScore: 73, insights: ["Business registration", "Property filings"], status: "Live", updated: "7h ago" },
  { id: "184", name: "Floyd Clark", location: "Pearland, TX", matchScore: 82, insights: ["Social media", "Court docket", "Voter record"], status: "Live", updated: "4h ago" },
  { id: "185", name: "Gladys Rodriguez", location: "Flint, MI", matchScore: 68, insights: ["Alias detected"], status: "Archived", updated: "2d ago" },
  { id: "186", name: "Alfred Lewis", location: "West Valley City, UT", matchScore: 95, insights: ["Utilities account", "Vehicle registration", "Professional license", "Business registration"], status: "Live", updated: "35m ago" },
  { id: "187", name: "Thelma Lee", location: "New Haven, CT", matchScore: 78, insights: ["Property filings", "Social media"], status: "Live", updated: "5h ago" },
  { id: "188", name: "Lloyd Walker", location: "Stamford, CT", matchScore: 69, insights: ["Court docket", "Voter record"], status: "Archived", updated: "5d ago" },
  { id: "189", name: "Stella Hall", location: "Hartford, CT", matchScore: 87, insights: ["Alias detected", "Utilities account", "Vehicle registration"], status: "Live", updated: "2h ago" },
  { id: "190", name: "Leon Allen", location: "Concord, NC", matchScore: 80, insights: ["Professional license", "Business registration"], status: "Live", updated: "4h ago" },
  { id: "191", name: "Agnes Young", location: "Gainesville, FL", matchScore: 74, insights: ["Property filings", "Social media"], status: "Live", updated: "6h ago" },
  { id: "192", name: "Vincent Hernandez", location: "Macon, GA", matchScore: 97, insights: ["Court docket", "Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "10m ago" },
  { id: "193", name: "Bernice King", location: "Vallejo, CA", matchScore: 62, insights: ["Vehicle registration"], status: "Archived", updated: "6d ago" },
  { id: "194", name: "Sidney Wright", location: "Independence, MO", matchScore: 85, insights: ["Professional license", "Business registration", "Property filings"], status: "Live", updated: "3h ago" },
  { id: "195", name: "Velma Lopez", location: "Athens, GA", matchScore: 71, insights: ["Social media", "Court docket"], status: "Live", updated: "8h ago" },
  { id: "196", name: "Chester Hill", location: "Murrieta, CA", matchScore: 92, insights: ["Voter record", "Alias detected", "Utilities account"], status: "Live", updated: "1h ago" },
  { id: "197", name: "Maxine Scott", location: "Rochester, MN", matchScore: 66, insights: ["Vehicle registration", "Professional license"], status: "Archived", updated: "3d ago" },
  { id: "198", name: "Willard Green", location: "Sterling Heights, MI", matchScore: 83, insights: ["Business registration", "Property filings", "Social media"], status: "Live", updated: "4h ago" },
  { id: "199", name: "Mabel Adams", location: "Ann Arbor, MI", matchScore: 75, insights: ["Court docket", "Voter record"], status: "Live", updated: "6h ago" },
  { id: "200", name: "Gilbert Baker", location: "Santa Maria, CA", matchScore: 90, insights: ["Alias detected", "Utilities account", "Vehicle registration"], status: "Live", updated: "2h ago" },
  { id: "201", name: "Pearl Nelson", location: "Lewisville, TX", matchScore: 63, insights: ["Professional license"], status: "Archived", updated: "4d ago" },
  { id: "202", name: "Harvey Carter", location: "Berkeley, CA", matchScore: 86, insights: ["Business registration", "Property filings", "Social media"], status: "Live", updated: "3h ago" },
  { id: "203", name: "Violet Mitchell", location: "Round Rock, TX", matchScore: 79, insights: ["Court docket", "Voter record", "Alias detected"], status: "Live", updated: "4h ago" },
];
